[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "{{ project_name }}.settings"

[tool.coverage.html]
directory = "static/coverage"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "class TestCase",
]

[tool.black]
line-length = 120
no-space-before-colon = "True"
